services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: llamas
      MYSQL_USER: llama
      MYSQL_PASSWORD: llamaPassword
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:4.0.5
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: llama
      RABBITMQ_DEFAULT_PASS: llamaPassword

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  mongodb_data:
  redis_data:
